"""
Semantic search over the university course catalog using sentence-transformers
embeddings and numpy cosine similarity.

Pre-built embeddings are loaded once at import time from course_embeddings.npy
and course_metadata.pkl (generated by build_embeddings.py).
"""

import os
import pickle

import numpy as np
from sentence_transformers import SentenceTransformer

_DIR = os.path.join(os.path.dirname(__file__), "..")
_EMBEDDINGS_PATH = os.path.join(_DIR, "course_embeddings.npy")
_METADATA_PATH = os.path.join(_DIR, "course_metadata.pkl")
_MODEL_NAME = "all-MiniLM-L6-v2"

# Load once at import time
_model = SentenceTransformer(_MODEL_NAME)
_embeddings: np.ndarray = np.load(_EMBEDDINGS_PATH)  # (N, 384), already normalized
with open(_METADATA_PATH, "rb") as _f:
    _metadata: list[dict] = pickle.load(_f)


def search_courses(query: str, top_k: int = 10) -> list[dict]:
    """Semantic search over available courses.

    Args:
        query: Natural language description of desired courses.
        top_k: Number of results to return. Defaults to 10.

    Returns:
        List of course dicts (most relevant first) with keys: course_code,
        name, section, crn, time, professor, credits, description.
    """
    query_embedding = _model.encode(query, normalize_embeddings=True)
    similarities = _embeddings @ query_embedding  # dot product on normalized = cosine sim
    top_indices = np.argpartition(similarities, -top_k)[-top_k:]
    top_indices = top_indices[np.argsort(similarities[top_indices])[::-1]]
    return [_metadata[i] for i in top_indices]
